service: ${self:custom.bucketName}-html-templates

plugins:
  - serverless-s3-sync
  - serverless-plugin-scripts

custom:
  bucketName: ${opt:stage, self:provider.stage}-eletype-email-templates

  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: templates

  prune:
    automatic: true
    number: 3
  scripts:
    hooks:
      "aws:deploy:finalize:cleanup": ../../scripts/deploySlackPost.sh ${self:service} ${opt:stage, self:provider.stage} "${self:provider.region}"

provider:
  name: aws
  profile: eletype
  region: us-east-1
  stage: dev

resources:
  Resources:
    TemplateBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
  Outputs:
    TemplateBucketName:
      Value:
        Ref: TemplateBucket
